server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: db_username
    password: db_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  security:
    jwt:
      secret-key: 368b38111be560242ac1202439b3aa8190811ebe560242ac120002
      expiration: 172800000 # 2 days
      refresh-token:
        expiration: 1209600000 # 7 days

logging:
  level:
    root: debug
    sql: info
    web: debug