server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  security:
    jwt:
      secret-key: 368b38111be560242ac1202439b3aa8190811ebe560242ac120002
      expiration: 172800000 # 2 days
      refresh-token:
        expiration: 1209600000 # 7 days

logging:
  level:
    root: info
    sql: info
    web: info