spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-user:5434/userdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-user:5434/userdb
    user: user
    password: password
    changeLog: classpath:/db/changelog/db-users.yaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

application:
  security:
    jwt:
      secret-key: 368b38111be560242ac1202439b3aa8190811ebe560242ac120002
      expiration: 172800000 # 2 days
      refresh-token:
        expiration: 1209600000 # 7 days