spring:
  application:
    name: student-ms
  datasource:
    url: jdbc:postgresql://postgres-student:5432/studentdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-student:5432/studentdb
    user: user
    password: password
    changeLog: classpath:/db/changelog/db-students.yaml

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
