server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: author-ms
          uri: lb://author-ms
          predicates:
            - Path=/api/v1/author/**
          filters:
            - AuthenticationFilterGatewayFilterFactory


        - id: student-ms
          uri: lb://student-ms
          predicates:
            - Path=/api/v1/student/**
          filters:
            - AuthenticationFilterGatewayFilterFactory


        - id: book-ms
          uri: lb://book-ms
          predicates:
            - Path=/api/v1/book/**
          filters:
            - AuthenticationFilterGatewayFilterFactory


        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

management:
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true