spring:
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://zipkin:9411/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    preferIpAddress: true

logging:
  level:
    root: error
    web: error
    sql: error

#server:
#  port: 5432